name: lumora_chat
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # Firebase & Cloudinary
  firebase_core: 2.27.0
  firebase_auth: 4.17.8
  cloud_firestore: 4.15.8
  cloudinary_public: ^0.23.1
  image_picker: ^1.0.4

  # UI Packages
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  
  # Notification Packages
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^18.0.1
  http: ^1.2.0
  googleapis_auth: ^1.6.0  # ✅ මේක අනිවාර්යයෙන් ඕන
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# ✅ Flutter Settings (Assets එන්නේ මෙතනට)
flutter:
  uses-material-design: true

  assets:
    - assets/service_account.json